"""D-STAR (JARL: STD6.0 англ., STD4.3C яп., сводка shogen, DV frame): заголовок — CRC-CCITT, свёрточный K=3 1/2, перемежение 24×28,
скремблер x^7+x^4+1; синхросигналы; CRC-32 режима DD. Сверка: dsd-fme (descramble.h, fcs.h — код G4KLX, GPL-2.0), проект dstar.py."""
import re, sys
sys.path.insert(0, __import__("os").path.dirname(__file__))
from obshchee import *

E = Tekst("istochniki/dstar/JARL_STD6_0_E.pdf")
J = Tekst("istochniki/dstar/JARL_STD4_3C.pdf")
S = Tekst("istochniki/dstar/JARL_shogen.pdf")
ZAPISI = []
desc = kod("dsd-fme", "include/descramble.h"); fcs = kod("dsd-fme", "include/fcs.h")
proj = open("/home/user/poiujnbhy/src/reportgen/potok/dstar.py").read()

# скремблер x^7+x^4+1, начальное — все единицы
s_scr = E.odna(r"S\(x\)=x7\+ x4\+1")[0]; s_scr0 = E.odna(r"Initialization is all 1")[0]
def skr(n):
    s, out = 0x7F, []
    for _ in range(n):
        b = ((s >> 6) ^ (s >> 3)) & 1; out.append(b); s = ((s << 1) | b) & 0x7F
    return out
tab = c_massiv(desc, "SCRAMBLER_TABLE_BITS")
assert len(tab) >= 660 and skr(len(tab)) == tab, "скремблер ≠ dsd-fme"
assert all(skr(127 + k)[127 + k - 1] == skr(k)[k - 1] for k in range(1, 20))                    # период 127 (m-последовательность)
# свёрточный K=3 (яп. STD4.3C: G1 = 1+D+D2, G2 = 1+D2)
s_cc = J.odna(r"G1\(D\) = 1 \+ D \+ D2")[0]; J.odna(r"G2\(D\) = 1 \+ D2")
s_cc_e = E.odna(r"convolutional symbol with a symbol factor of 1/2 and a")[0]
assert dfree([0b111, 0b101], 3) == 5
# перемежение: матрица 24 строки × 28 столбцов (660 бит): строка r содержит r, r+24, …
kus, s_il = E.kusok(r"interleave structure MATRIX", r"=====СТР 9[3-9]|Ap3", posl=True)
chisla = [int(x) for x in re.findall(r"(?<![\d.])\d+(?![\d.])", kus)]
stroki = {}
for r in range(24):
    ozh = [r + 24 * c for c in range(28) if r + 24 * c < 660]
    s_ = " " + " ".join(map(str, chisla)) + " "
    assert " " + " ".join(map(str, ozh)) + " " in s_, r
    stroki[r] = ozh
assert sum(len(v) for v in stroki.values()) == 660 and sorted(sum(stroki.values(), [])) == list(range(660))
# эфирный порядок = чтение строк матрицы по порядку (строки 0–11 по 28, 12–23 по 27): эфирный i → кодовый k
efir = sum((stroki[r] for r in range(24)), [])
def deil_dsd():
    k, out = 0, []
    for loop in range(660):
        out.append(k); k += 24
        if k >= 672: k -= 671
        elif k >= 660: k -= 647
    return out
assert deil_dsd() == efir, "перемежение ≠ dsd-fme deinterleave"
def proj_il():
    m = []
    for i in range(660):
        if i < 12 * 28: m.append((i % 28) * 24 + i // 28)
        else: j = i - 12 * 28; m.append((j % 27) * 24 + 12 + j // 27)
    return m
assert "места.append((i % 28) * 24 + i // 28)" in proj and proj_il() == efir
# CRC
s_fcs = E.odna(r"generated by the following equation according to CRC-CCITT")[0]
s_crc32 = E.odna(r"G\(x\) = x32\+ x26\+ x23\+ x22\+ x16\+ x12\+ x11\+ x10\+ x8\+ x7\+ x5\+ x4\+ x2\+ x\+ 1")[0]
tf = open(os.path.join(KOREN, fcs)).read()
assert "m_crc=0xFFFF;" in tf and "(m_crc >> 8) ^ ccittTab[tmp]" in tf and c_massiv(fcs, "ccittTab")[1] == 0x1189   # отражённая таблица 0x8408
# синхросигналы
s_fs = E.odna(r"Frame synchronization\" shall be 15 bits \(111011001010000\)")[0]
s_ds = E.odna(r"“101010101011010001101000”")[0]
s_end = E.odna(r"32 bits \+ 15 bits “000100110101111” \+ 0")[0]
assert int("101010101011010001101000", 2) == 0xAAB468 and "СИНХРО_ДАННЫХ = 0xAAB468" in proj
assert int("1010101010101010" + "000100110101111" + "0", 2) == 0xAAAA135E and "КОНЕЦ = 0xAAAA135E" in proj
tablica("dstar_zagolovok", {"skrembler_660": skr(660), "efir_v_kod_660": efir, "matrica_24x28": [stroki[r] for r in range(24)]},
        "D-STAR заголовок: ПСП скремблера (660 бит), перемежение (эфирный номер → номер кодового бита), матрица 24×28",
        [E.ist(s_scr, "Ap1.1"), E.ist(s_il, "Ap2.2 interleave structure MATRIX"), ist_kod(desc, "SCRAMBLER_TABLE_BITS"), ist_kod(desc, "void deinterleave")],
        "скремблер из x^7+x^4+1 (все 1) = SCRAMBLER_TABLE_BITS dsd-fme; все 24 строки матрицы найдены в тексте; порядок = deinterleave dsd-fme = ПЕРЕМЕЖЕНИЕ проекта")

def rec(imya, vid, par, gde, ist, prov, sl):
    ZAPISI.append({"имя": imya, "семейство": "D-STAR (JARL)", "область": "mobilnaya", "вид": vid, "параметры": par, "где применяется": gde,
                   "источник": ist, "проверка": prov, "сложность внедрения": sl})
EST = "ЕСТЬ в проекте: dstar.py (заголовок: скремблер, перемежение, свёртка/витерби, CRC; синхро данных, медленные данные)"
rec("D-STAR заголовок: CRC-CCITT + свёрточный K=3 1/2 + перемежение 24×28 + скремблер x^7+x^4+1", "каскадный: CRC + свёрточный K=3",
    {"заголовок": "41 байт (флаги 3, позывные 4×8 + 4, P_FCS 2) = 328 бит + 2 нулевых (хвост) = 330 → 660",
     "свёрточный": "K=3, G1 = 1+D+D², G2 = 1+D² (7, 5 восьм.), d_free = 5; вход байтами с младшего бита",
     "P_FCS": "CRC-CCITT x16+x12+x5+1, отражённый (0x8408), начальное 0xFFFF, инверсия, младший байт первым (= CRC-16/X-25)",
     "перемежение": "660 бит в матрицу 24×28 по столбцам (строки 0–11 — 28 бит, 12–23 — 27), передача строками — tablicy/dstar_zagolovok.json",
     "скремблер": "S(x) = x7+x4+1, начальное 1111111 с начала заголовка; символы — младшим битом вперёд", "модуляция": "GMSK 4800 бит/с (DV)"},
    "D-STAR DV (голос/медленные данные), DD (заголовок)", [E.ist(s_cc_e, "Ap2.1"), J.ist(s_cc, "STD4.3C: G1, G2"), E.ist(s_il, "Ap2.2"), E.ist(s_scr, "Ap1"), E.ist(s_fcs, "P_FCS")],
    "скремблер и перемежение = dsd-fme (descramble.h, код G4KLX); CRC = dsd-fme fcs.h (0xFFFF, таблица 0x8408); = проект dstar.py", EST)
rec("D-STAR синхросигналы: кадровая 15 бит, синхро данных 24 бита, конец передачи", "синхрослово",
    {"кадровая": "111011001010000 (после 64-битной 1010… преамбулы)", "синхро данных": "1010101010 1101000 1101000 = 0xAAB468 (каждый 21-й кадр)",
     "конец": "32 бита 1010… + 000100110101111 + 0 (0xAAAA135E в конце)", "кадр DV": "72 бита AMBE + 24 бита данных = 96 бит, сверхкадр 21",
     "медленные данные": "скремблируются XOR 0x70 0x4F 0x93"},
    "поиск D-STAR в потоке GMSK", [E.ist(s_fs, "frame sync"), E.ist(s_ds, "sync flag"), E.ist(s_end, "end")], "= константы проекта dstar.py; = DSTAR_DV_frame3_en (кадровая)", EST)
rec("D-STAR DD: CRC-32 (ISO 3309)", "CRC-подобный", {"g": "x32+x26+x23+x22+x16+x12+x11+x10+x8+x7+x5+x4+x2+x+1 (CRC-32 IEEE, как Ethernet FCS)"},
    "D-STAR DD (128 кбит/с, Ethernet-кадры)", [E.ist(s_crc32, "FCS DD")], "многочлен = CRC-32 каталога проекта", "есть CRC-32 (crc_katalog.py)")

if __name__ == "__main__":
    print(len(ZAPISI), "записей")
