"""Скремблеры: собственные записи по первоисточникам (МСЭ-T V.22bis/V.26ter/V.27bis/V.27ter/V.29/V.32/V.36/V.37/V.38,
I.432.1; IEEE 802.3-2012 — файлы области provod; MIL-STD-188-141B) + сводная таблица скремблеров всех областей
(tablicy/skremblery/svodka_oblastey.json — записи efir/kosmos/mobilnaya/provod с их источниками).
Проверки (assert): многочлен прочитан из текста источника регулярным выражением (не вписан); примитивность/период
LFSR рассчитаны (gf2); совпадение со вторым источником (другая Рекомендация с тем же скремблером, skrembler.ИЗВЕСТНЫЕ
проекта, записи других областей)."""
import json, os, re, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from zap import KOR, I, Z, sohranit, stroka, gde
from gf2 import primitive, irreducible, order_x
IST = 'istochniki/skremblery/'
P8023 = '../provod/tekst/ieee8023/standart/802.3-2012_section%d.pdf.txt'
P8023_PDF = '../provod/istochniki/ieee8023/standart/802.3-2012_section%d.pdf'
proekt = open('/home/user/poiujnbhy/src/reportgen/potok/skrembler.py').read()
izv = {tuple(int(x) for x in re.findall(r'\d+', m.group(2))): m.group(1) for m in re.finditer(r'"([^"]+)": \(([\d, ]+)\),', proekt)}


def txt(f): return open(os.path.join(KOR, f), encoding='utf-8', errors='replace').read()


def polinom(f, obrazec_re):
    """Найти многочлен в тексте; вернуть (степени отводов, найденная строка)."""
    t = txt(f)
    m = re.search(obrazec_re, t)
    assert m, (f, obrazec_re)
    s = m.group(0)
    st = sorted(set(int(x) for x in re.findall(r'x\s*[-–−]?\s*(\d+)', s)), reverse=True)
    return st, s.replace('\n', ' ')


def info(st):
    m = max(st); p = (1 << m) | 1
    for e in st:
        if e != m: p |= 1 << e
    pr = primitive(p); per = (1 << m) - 1 if pr else order_x(p, 1 << 22)
    return p, pr, per


zap = []; tabl = []


def dobavit(imya, vid, st, dop, gde_prim, ist, prov_dop, sl=None, sem='Скремблеры стандартов'):
    p, pr, per = info(st)
    otv = tuple(sorted(e for e in st if e != 0))
    v_proekte = izv.get(otv)
    pr_txt = 'многочлен прочитан из текста; ' + ('примитивен (период 2^%d−1 = %d)' % (max(st), per) if pr else 'НЕ примитивен (период %s)' % per)
    if prov_dop: pr_txt += '; ' + prov_dop
    if sl is None:
        sl = ('ЕСТЬ в проекте: skrembler.ИЗВЕСТНЫЕ «%s», skrembler.снять/аддитивный' % v_proekte) if v_proekte else \
             'ЧАСТИЧНО: skrembler.py находит такие скремблеры вслепую (Берлекэмп — Мэсси / перебор отводов); в списке ИЗВЕСТНЫЕ этого нет — добавить для подписи'
    par = {'многочлен': ' + '.join(('x^%d' % e if e > 1 else ('x' if e == 1 else '1')) for e in sorted(st, reverse=True)) + ' (степени задержек, как в источнике)',
           'тип': vid, 'hex': '0x%X' % p}
    par.update(dop)
    zap.append(Z(imya, sem, 'скремблер', par, gde_prim, ist, pr_txt, sl))
    tabl.append(dict(имя=imya, тип=vid, степени=st, hex='0x%X' % p, примитивен=pr, период=per, источник=ist[0]['файл'], область='obshchie'))


# --- МСЭ-T V-серия ---
f = IST + 'T-REC-V.22bis-198811-I.pdf.txt'
st, s = polinom(f, r'generating polynomial 1 ⊕ x-14 ⊕ x-17')
dobavit('Скремблер V.22bis (самосинхронизирующийся 1 + x^-14 + x^-17)', 'самосинхронизирующийся (мультипликативный)', st,
        {'защита': 'после 64 подряд единиц на входе дескремблера инвертировать следующий выход (п. 5.2); то же у V.22',
         'начальное': 'не нужно (самосинхронизация)'}, 'модемы V.22/V.22bis (1200/2400 бит/с), V.32bis в режиме V.22bis, ВЧ-модемы',
        [I(f[:-4], gde(f, 'A self synchronizing scrambler having the generating polynomial'))], 'тот же многочлен в проекте (V.22/V.22bis)')
f = IST + 'T-REC-V.27ter-198811-I.pdf.txt'
st, s = polinom(f, r'Scrambler\nA self-synchronizing scrambler/descrambler having the generating polynomial:\n1 \+ x-6 \+ x-7')
f2 = IST + 'T-REC-V.27bis-198811-I.pdf.txt'
st2, _ = polinom(f2, r'A self-synchronizing scrambler/descrambler having the generating polynomial:\n1 \+ x -6 \+ x -7')
assert st == st2
dobavit('Скремблер V.27/V.27bis/V.27ter (1 + x^-6 + x^-7)', 'самосинхронизирующийся', st,
        {'защита': 'от повторяющихся комбинаций с периодами 1, 2, 3, 4, 6, 8, 9 и 12 бит (рис. I-2); V.27bis/ter = V.27 + защита от периода 8',
         'обучение': 'тот же 1 + x^-6 + x^-7 — генератор ПСП для настройки эквалайзера (каждый третий бит, 0°/180°)'},
        'факс-модемы V.27ter (G3, 2400/4800 бит/с), выделенные V.27bis',
        [I(f[:-4], gde(f, 'A self-synchronizing scrambler/descrambler having the generating polynomial:')), I(f2[:-4], gde(f2, 'A self-synchronizing scrambler/descrambler having the generating polynomial:'))],
        'V.27bis и V.27ter — один многочлен (два документа)')
f = IST + 'T-REC-V.29-198811-I.pdf.txt'
st, s = polinom(f, r'generating polynomial 1 \+ x-18 \+ x-23')
stp, _ = polinom(f, r'generated by the polynomial:\n1 \+ x-6 \+ x-7')
f3 = IST + 'T-REC-V.32-199303-I.pdf.txt'
stc, _ = polinom(f3, r'\(GPC\)\s+=\s+1\s+\+\s+x–18\s+\+\s+x–23')
sta, _ = polinom(f3, r'\(GPA\)\s+=\s+1\s+\+\s+x–5\s+\+\s+x–23')
f4 = IST + 'T-REC-V.26ter-198811-I.pdf.txt'
st4c, s4 = polinom(f4, r'GPC = 1 \+ x-18 \+ x-23 or GPA = 1 \+ x-5 \+ x-23')
f5 = IST + 'T-REC-V.38-199610-I.pdf.txt'
st5, _ = polinom(f5, r'generating polynomial 1 \+ x–18 \+ x–23')
assert st == stc == st5 and sorted(st4c) == sorted(set(stc + sta)), (st, stc, st5, st4c, sta)
f34 = IST + 'T-REC-V.34-199802-I.pdf.txt'
st34c, _ = polinom(f34, r'\(GPC\)\s+=\s+1\s+\+\s+x–18\s+\+\s+x–23')
st34a, _ = polinom(f34, r'\(GPA\)\s+=\s+1\s+\+\s+x–5\s+\+\s+x–23')
f33 = IST + 'T-REC-V.33-198811-I.pdf.txt'
st33, _ = polinom(f33, r'generating polynomial 1 \+ x-18 \+ x-23')
f90 = IST + 'T-REC-V.90-199809-I.pdf.txt'
assert 'using the generating\npolynomial, GPC, in equation 7-1/V.34' in txt(f90) and 'polynomial, GPA, in equation 7-2/V.34' in txt(f90)
assert st34c == stc == st33 and st34a == sta, (st34c, st34a, st33)
f17 = IST + 'T-REC-V.17-199102-I.pdf.txt'
st17, _ = polinom(f17, r'generator polynomial:\n1 \+ x–18 \+ x–23')
f92 = IST + 'T-REC-V.92-200011-I.pdf.txt'
assert 'same as those given in clause 5/V.90' in txt(f92) and 'polynomial, GPA, in equation 7-2/V.34' in txt(f92)
assert st17 == stc, st17
dobavit('Скремблер V.29 / V.32 / V.33 / V.17 / V.26ter / V.38, вызывающий GPC (1 + x^-18 + x^-23)', 'самосинхронизирующийся', st,
        {'обучение V.29': '1 + x^-6 + x^-7 (сегмент 3, точки C/D)', 'дуплекс': 'V.32/V.26ter: вызывающий модем скремблирует GPC, отвечающий — GPA (1 + x^-5 + x^-23)'},
        'модемы V.29 (факс 9600), V.32/V.32bis, V.33, V.17, V.26ter, V.38 (опц.), V.34 (вызывающий), V.90/V.92 (цифровой модем)',
        [I(f[:-4], gde(f, 'A self-synchronizing scrambler/descrambler having the generating polynomial 1 + x-18 + x-23')), I(f3[:-4], gde(f3, 'Call mode modem generating polynomial')),
         I(f4[:-4], gde(f4, 'The message polynomial is divided by the generating polynomial GPC')), I(f5[:-4], gde(f5, 'generating polynomial 1 + x–18 + x–23')),
         I(f34[:-4], gde(f34, 'Call mode modem generating polynomial')), I(f33[:-4], gde(f33, 'generating polynomial 1 + x-18 + x-23')), I(f90[:-4], gde(f90, 'polynomial, GPC, in equation 7-1/V.34')),
         I(f17[:-4], gde(f17, 'self-synchronizing scrambler/descrambler with the generator polynomial')), I(f92[:-4], gde(f92, 'same as those given in clause 5/V.90'))],
        'один многочлен в V.29, V.32, V.26ter, V.38, V.33, V.17, V.34, V.90 и V.92 (цифровой модем — GPC по 7-1/V.34 через 5/V.90) — девять документов, сверено assert')
dobavit('Скремблер V.32 / V.26ter / V.34, отвечающий GPA (1 + x^-5 + x^-23)', 'самосинхронизирующийся', sta,
        {'дуплекс': 'отвечающий модем скремблирует GPA, дескремблирует GPC'}, 'модемы V.32/V.32bis/V.26ter, V.34 (отвечающий), V.90/V.92 (аналоговый модем)',
        [I(f3[:-4], gde(f3, 'Answer mode modem generating polynomial')), I(f4[:-4], gde(f4, 'The message polynomial is divided by the generating polynomial GPC')),
         I(f34[:-4], gde(f34, 'Answer mode modem generating polynomial')), I(f90[:-4], gde(f90, 'polynomial, GPA, in equation 7-2/V.34')), I(f92[:-4], gde(f92, 'polynomial, GPA, in equation 7-2/V.34'))],
        'V.32, V.26ter, V.34 и V.90 (аналоговый модем) — GPA; V.32 и V.26ter — один многочлен (взаимный к GPC: x^23·GPC(1/x))')
dobavit('ПСП обучения V.29 / V.27 (1 + x^-6 + x^-7)', 'аддитивный генератор ПСП (обучающая последовательность)', stp,
        {'применение': 'сегмент обучения эквалайзера: 0 → точка C, 1 → точка D (V.29); фазы 0°/180° по каждому 3-му биту (V.27ter)'},
        'преамбулы модемов V.29, V.27ter', [I(f[:-4], gde(f, 'signalling rates. The equalizer conditioning pattern is a pseudo-random sequence'))], '', sl='НЕТ: преамбулы модемов в проекте не опознаются (нужна плоскость символов)')
f6 = IST + 'T-REC-V.36-198811-I.pdf.txt'
t6 = txt(f6)
assert 'twentieth and third earlier transmitted bits' in t6 and 'q = (31 + 32 r)' in t6
dobavit('Скремблер V.36/V.37 (V.35-типа): нечётность с 3-м и 20-м предыдущими битами + детектор неблагоприятного состояния', 'самосинхронизирующийся с инверсией и защитой', [20, 3, 0],
        {'правило': 'следующий бит даёт НЕЧЁТНУЮ чётность вместе с 20-м и 3-м ранее переданными битами и входным битом; при «неблагоприятном состоянии» — чётную',
         'неблагоприятное состояние': 'p-й и (p+8)-й ранее переданные биты совпадали для всех p = 1…q, q = 31 + 32r (прил. I.2)',
         'начальное': 'любые 20 бит; дескремблер синхронизируется за ≥ 20 бит'},
        'групповые модемы V.36 (48–72 кбит/с), V.37; та же схема — V.35 (отменена)',
        [I(f6[:-4], gde(f6, 'with the twentieth and third earlier transmitted bits'))], 'правило прочитано из текста прил. I.2 (двадцатый и третий биты); то же в V.37',
        sl=None)
st38, _ = polinom(f5, r'polynomial 1 \+ x–4 \+ x–7')
dobavit('Скремблер шлейфа V.38 (1 + x^-4 + x^-7, команда «шлейф 2»)', 'самосинхронизирующийся (сигнализация шлейфа)', st38,
        {'применение': 'скремблирование двоичного 0 для команды удалённого шлейфа 2/2b (п. 6.1.1)'}, 'DCE V.38 (цифровые выделенные 48/56/64 кбит/с)',
        [I(f5[:-4], gde(f5, 'scrambling of a binary 0 with the polynomial 1 + x–4 + x–7'))], '')
# --- I.432.1 ---
f = IST + 'T-REC-I.432.1-199902-I.pdf.txt'
st, _ = polinom(f, r'self-synchronizing scrambler with polynomial x43 \+ 1')
dobavit('Скремблер ячеек ATM x^43 + 1 (SDH-интерфейс)', 'самосинхронизирующийся, нагрузка ячейки (48 байт) без заголовка', st,
        {'начальное': 'не нужно; размножение ошибок ×2', 'HEC': 'x^8 + x^2 + x + 1 (+ 0x55 по I.432.1) — заголовок не скремблируется'},
        'ATM по SDH/SONET (I.432.1), POS (RFC 2615), GFP (G.7041 — тот же x^43+1)', [I(f[:-4], gde(f, 'a self-synchronizing scrambler with polynomial x43 + 1.'))],
        'совпадает с проектом (SDH/SONET, ATM, POS)')
st, _ = polinom(f, r'pseudo-random sequence polynomial is:\nx31 \+ x28 \+1')
dobavit('Распределённый выборочный скремблер ATM x^31 + x^28 + 1 (интерфейс на ячейках)', 'аддитивный, синхронизация выборками (2 бита на ячейку)', st,
        {'правило': 'ПСП складывается со всей ячейкой кроме HEC; HEC пересчитывается с учётом ПСП; 2 бита выборки в HEC; 16 ячеек дают 31 выборку для синхронизации'},
        'ATM на ячейках (cell-based physical layer, I.432.1)', [I(f[:-4], gde(f, 'The pseudo-random sequence polynomial is:'))], '')
# --- IEEE 802.3-2012 (файлы области provod) ---
def d8023(sec, obr, start=0):
    f = P8023 % sec
    return I((P8023_PDF % sec), gde(f, obr, start), 'https://standards.ieee.org/ieee/802.3/4422/ (802.3-2012, файлы области provod)')
t4 = txt(P8023 % 4)
t4n = re.sub(r'\s+', ' ', t4)
assert 'G x ( ) 1 x39 x58 + + =' in t4n and 'G x ( ) 1 x19 x58 + + =' in t4n
dobavit('Скремблер 64b/66b IEEE 802.3 cl.49 (1 + x^39 + x^58)', 'самосинхронизирующийся, только 64 бита нагрузки (синхрозаголовок 2 бита не скремблируется)', [58, 39, 0],
        {'начальное': 'не задано (непрерывно)', 'порядок': 'младший член — последний вошедший бит (сноска 7 cl.49); проверка — по рис. 49-8',
         'тот же': '10GBASE-R/KR, 25/40/100GBASE-R, 10GBASE-T (cl.55 MASTER), Fibre Channel 10G/16G, InfiniBand FDR'},
        'Ethernet 10G…100G (PCS 64b/66b), 10GBASE-T', [d8023(4, '49.2.6 Scrambler'), d8023(4, '55.3.2.2.16 PCS scrambler')], 'cl.49 и cl.55 (MASTER) — один многочлен; совпадает с проектом (10GBASE-R)')
dobavit('Скремблер 10GBASE-T cl.55, SLAVE (1 + x^19 + x^58)', 'самосинхронизирующийся', [58, 19, 0], {'MASTER': '1 + x^39 + x^58'}, 'Ethernet 10GBASE-T (ведомая сторона)',
        [d8023(4, '55.3.2.2.16 PCS scrambler')], 'формула (55-2) в тексте')
t2 = txt(P8023 % 2)
assert 'gM x ( ) 1 x13 x33 + + = gS x ( ) 1 x20 x33 + + =' in re.sub(r'\s+', ' ', t2)
dobavit('Боковой (side-stream) скремблер 100BASE-T2 / 1000BASE-T, MASTER (1 + x^13 + x^33)', 'аддитивный «боковой» (side-stream), регистр 33 бита', [33, 13, 0],
        {'SLAVE': '1 + x^20 + x^33 (дескремблер MASTER — g´M = 1 + x^20 + x^33)', 'начальное': 'произвольное ненулевое (сброс PCS)',
         'тест 1000BASE-T': 'test mode 4: x^11 + x^9 + 1 (биты Scr[8] ⊕ Scr[10])'},
        'Ethernet 100BASE-T2 (cl.32), 1000BASE-T (cl.40)', [d8023(2, '32.3.1.2.1 Side-stream scrambler polynomials', 30000), d8023(3, '40.3.1.3.1 Side-stream scrambler polynomials', 10000)],
        'cl.32 и cl.40 — одна пара многочленов')
dobavit('Боковой скремблер 100BASE-T2 / 1000BASE-T, SLAVE (1 + x^20 + x^33)', 'аддитивный side-stream', [33, 20, 0], {}, 'Ethernet 100BASE-T2, 1000BASE-T (ведомая сторона)',
        [d8023(2, '32.3.1.3.1 Receiver descrambler polynomials', 30000)], 'взаимный к MASTER')
dobavit('Тестовая ПСП 1000BASE-T test mode 4 (x^11 + x^9 + 1)', 'генератор ПСП (тест передатчика)', [11, 9, 0], {'правило': 'Scr[0] = Scr[8] ⊕ Scr[10], шаг 8 нс'},
        'Ethernet 1000BASE-T (испытания)', [d8023(3, 'scrambler generator polynomial, bit generation, and level mappings:', 15000), d8023(3, 'Bits Scrn[8] and Scrn[10] are exclusive OR', 15000)], 'отводы 8 и 10 (с нуля) = степени 9 и 11', sl='ЧАСТИЧНО: аддитивная ПСП находится skrembler.аддитивный')
t1 = txt(P8023 % 1)
assert 'G(x) = 1 + x–1 + x–18 + x–19 + x–23 + x–24' in t1
dobavit('Скремблер 10BROAD36 cl.11 (скремблер + дифференциальный кодер ≡ деление на 1 + x^-1 + x^-18 + x^-19 + x^-23 + x^-24)', 'самосинхронизирующийся + дифференциальное кодирование', [24, 23, 19, 18, 1, 0],
        {'разложение': '(1 + x^-1)(1 + x^-18 + x^-23) — дифференциальный кодер × скремблер V.29-типа', 'сброс': 'для каждого нового пакета'},
        'Ethernet 10BROAD36 (широкополосный по коаксиалу)', [d8023(1, 'G(x) = 1 + x–1 + x–18 + x–19 + x–23 + x–24')], '')
# проверка разложения 10BROAD36
from gf2 import mul
assert mul(0b11, (1 << 23) | (1 << 18) | 1) == (1 << 24) | (1 << 23) | (1 << 19) | (1 << 18) | 2 | 1
zap[-1]['проверка'] += '; разложение (1+x)(1+x^18+x^23) проверено умножением в GF(2)'
# G.707 (файлы области provod): многочлен кадрового скремблера STM-N
def g707_ist():
    ft = os.path.join(KOR, '..', 'provod', 'tekst', 'itu', 'T-REC-G.707-200701-I.pdf.txt')
    L = open(ft, encoding='utf-8', errors='replace').read().split('\n')
    n = next(i + 1 for i, l in enumerate(L) if 'The generating polynomial shall be 1 + X6 + X7' in l)
    assert any('reset to "1111111"' in l for l in L[n:n + 15])
    stp = max(int(m.group(1)) for l in L[:n] for m in [re.search(r'=====СТР (\d+)=====', l)] if m)
    return I('../provod/istochniki/itu/T-REC-G.707-200701-I.pdf', 'стр. %d PDF, п. 6.6 (строка %d в ../provod/tekst/itu/T-REC-G.707-200701-I.pdf.txt)' % (stp, n),
             'https://www.itu.int/rec/T-REC-G.707-200701-I/en (файл области provod)')
# WIS cl.50 → SONET
dobavit('Кадровый скремблер SONET/SDH (1 + x^6 + x^7), сброс 1111111 после Z0 — WIS cl.50', 'аддитивный, кадрово-синхронный', [7, 6, 0],
        {'сброс': '1111111 перед октетом после последнего Z0 каждого кадра WIS', 'порядок': 'старший бит октета первым', 'основа': 'ATIS-0900105.2008 п. 10.3 (многочлен — по G.707, область provod)'},
        '10GBASE-W (WIS), SONET/SDH STM-N', [d8023(4, '50.3.3.1 Scrambler polynomial'), g707_ist()], 'многочлен 1 + X6 + X7 и сброс «1111111» прочитаны из G.707 п. 6.6 (assert); 802.3 cl.50 — сброс и порядок бит WIS',
        sl='ЕСТЬ в проекте: sdh.py (кадровый скремблер STM-N), otn.py')
# MIL-STD-188-141B прил. C
fm = 'istochniki/golei/MIL-STD-188-141B_ALE.pdf.txt'
tm = txt(fm)
assert '(0xAB91 + FTcount) mod 0x 10000' in tm
json.dump(tabl, open(os.path.join(KOR, 'tablicy', 'skremblery', 'sobstvennye.json'), 'w'), ensure_ascii=False, indent=1)
# сводная по областям
sv = []
for a in ('efir', 'kosmos', 'mobilnaya', 'provod'):
    for z in json.load(open(os.path.join(KOR, '..', a, 'katalog.json'))):
        v = str(z.get('вид', '')).lower()
        if 'скремблер' in v or 'рандомиз' in v or 'псп' in v or 'скремблер' in z.get('имя', '').lower() or 'рандомиз' in z.get('имя', '').lower():
            sv.append(dict(область=a, имя=z['имя'], вид=z.get('вид'), параметры=z.get('параметры'), источник=[dict(s, файл='../%s/%s' % (a, s.get('файл', ''))) for s in z.get('источник', [])],
                           проверка=z.get('проверка')))
json.dump(sv, open(os.path.join(KOR, 'tablicy', 'skremblery', 'svodka_oblastey.json'), 'w'), ensure_ascii=False, indent=1)
print('скремблеров своих', len(tabl), 'в других областях', len(sv))
sohranit('skremblery', zap)
