"""IEEE 802.11ad (DMG, 60 ГГц) и 802.11ay (EDMG): LDPC 672 (1/2, 5/8, 3/4, 13/16), 7/8 (624) и 1344.

Стандарт IEEE 802.11ad-2012 платный; матрицы — из открытых документов рабочей группы IEEE 802.11
(mentor.ieee.org, скачаны 2026-09-30):

- 11-10/0433r2 «CP specification» (TGad, 05/2010) — текст объединённого предложения, ставший черновиком
  D0.1: п. 21.3.8 «Common LDPC parity matrices», табл. 69–72 (четыре базовые матрицы 16 столбцов,
  Z = 42; пустая клетка — нулевой блок; «Pi … cyclically shifting the columns to the right by i»);
  кодер систематический: c = (b1…bk, p1…p(n−k)), H·cᵀ = 0 (21.5.3.2.2.2, 21.6.3.2.2);
- 11-16/0676r1 (Samsung, TGay, 05/2016), слайды 5–8 — те же четыре матрицы как «11ad base matrix»
  (второй источник, число в число), табл. слайдов 5–8 — матрицы подъёма 1344; слайд 18 — число
  6-циклов графа Таннера L672 (11ad) и L1344 — сверяется подсчётом;
- 11-16/0692r0 (Samsung, TGay) — текст SFD: правило подъёма («0» → [[Pi, −], [−, Pi]], «1» →
  [[−, Pi], [Pi, −]], «−1» → нули) и те же матрицы подъёма;
- 11-17/1061r1 (Huawei, TGay) — 7/8 длины 1344: подъём 3/4 по табл. 30 и сумма строк 1+5, 2+6, 3+7,
  4+8 даёт табл. 31 — сверяется (и тем самым ещё раз матрица 3/4 802.11ad);
- 11-16/1495r1 (Huawei, TGay), слайд 2: «7/8 … adopted in 802.11REVmc … generated by puncturing the
  first 48 parity bits from rate 13/16 … codeword length is 624».

Третий голос (только сверка, в репозиторий не кладётся — нет лицензии): 802.11ad-phy-sim
(github.com/jirimilos/802.11ad-phy-sim, f986bfc, LDPC_matrix.m, «case 672» и «case 624»), если путь
передан первым аргументом.

Пишет src/reportgen/potok/data/ldpc_80211ad.json. Запуск из корня репозитория.
"""
import json
import os
import re
import sys
import zipfile

import numpy as np

ZDES = os.path.dirname(os.path.abspath(__file__))
K0 = os.path.normpath(os.path.join(ZDES, '..'))
KOREN = os.path.normpath(os.path.join(K0, '..', '..'))
sys.path.insert(0, os.path.join(KOREN, 'src'))
from reportgen.potok import gf2  # noqa: E402

ST = os.path.join(K0, 'standarty')
Z = 42


def tablicy_docx(imya):
    """Таблицы docx: ряды клеток (текст клетки; пустая — '')."""
    x = zipfile.ZipFile(os.path.join(ST, imya)).read('word/document.xml').decode()
    itog = []
    for t in re.findall(r'<w:tbl>.*?</w:tbl>', x, re.S):
        ryady = []
        for r in re.findall(r'<w:tr[ >].*?</w:tr>', t, re.S):
            ryady.append([''.join(re.findall(r'<w:t(?: [^>]*)?>([^<]*)</w:t>', c)).strip()
                          for c in re.findall(r'<w:tc>.*?</w:tc>', r, re.S)])
        itog.append(ryady)
    return itog


def tablicy_pptx(imya, slajd):
    z = zipfile.ZipFile(os.path.join(ST, imya))
    x = z.read('ppt/slides/slide%d.xml' % slajd).decode()
    itog = []
    for t in re.findall(r'<a:tbl>.*?</a:tbl>', x, re.S):
        itog.append([[''.join(re.findall(r'<a:t>([^<]*)</a:t>', c)).strip() for c in re.findall(r'<a:tc.*?</a:tc>', r, re.S)]
                     for r in re.findall(r'<a:tr .*?</a:tr>', t, re.S)])
    return itog, ' '.join(re.findall(r'<a:t>([^<]*)</a:t>', x))


def chisla(tablica, pusto=-1):
    return [[int(c) if c not in ('', '-') else pusto for c in r] for r in tablica]


def iz_bazy(baza, z=Z):
    """H по базовой матрице: s ≥ 0 — единичная Z×Z со столбцами, сдвинутыми вправо на s (21.3.8)."""
    R, C = len(baza), len(baza[0])
    H = np.zeros((R * z, C * z), np.uint8)
    for r in range(R):
        for c in range(C):
            s = baza[r][c]
            if s >= 0:
                i = np.arange(z)
                H[r * z + i, c * z + (i + s) % z] ^= 1
    return H


def shest_ciklov(H):
    """Число 6-циклов графа Таннера: по тройкам разных проверок (a, b, c) и разным переменным
    x ∈ N(a)∩N(b), y ∈ N(b)∩N(c), w ∈ N(c)∩N(a): tr(P₀³) − 3·Σ_v (d_v − 2)·Σ_{a≠b∈N(v)} P₀[a,b]
    + 2·Σ_v d_v(d_v − 1)(d_v − 2), делённое на 6 (P₀ = H·Hᵀ без диагонали)."""
    Hi = H.astype(np.int64)
    P = Hi @ Hi.T
    np.fill_diagonal(P, 0)
    sled = int(np.trace(P @ P @ P))
    d = Hi.sum(axis=0)
    popr = 0
    for v in range(H.shape[1]):
        s = np.flatnonzero(Hi[:, v])
        popr += (d[v] - 2) * int(P[np.ix_(s, s)].sum())
    troiki = int((d * (d - 1) * (d - 2)).sum())
    ch = sled - 3 * popr + 2 * troiki
    assert ch % 6 == 0, ch
    return ch // 6


# -- 802.11ad: четыре матрицы (11-10/0433r2, табл. 69–72) ---------------------------------------------
T = [t for t in tablicy_docx('IEEE_802.11-10-0433-02_TGad_CP_specification.docx')
     if t and all(len(r) == 16 for r in t) and all(re.fullmatch(r'\d*', c) for r in t for c in r)]
assert [len(t) for t in T] == [8, 6, 4, 3], [len(t) for t in T]
AD = dict(zip(('1/2', '5/8', '3/4', '13/16'), (chisla(t) for t in T)))
tekst = open(os.path.join(ST, 'IEEE_802.11-10-0433-02_TGad_CP_specification.docx.txt'), encoding='utf-8').read()
assert 'cyclic-permutation sub-matrix Pi obtained from the Z x Z identity matrix by cyclically shifting the ' \
       'columns to the right by i elements' in tekst
for skor, strok in (('1/2', 336), ('5/8', 252), ('3/4', 168), ('13/16', 126)):
    assert 'Rate-%s LDPC code matrix H = %d rows x 672 columns, Z = 42' % (skor, strok) in tekst
    assert len(AD[skor]) * Z == strok
assert all(-1 <= s < Z for b in AD.values() for r in b for s in r)
print('802.11ad: 11-10/0433r2, табл. 69–72 — четыре матрицы 16 столбцов, Z = 42 (8, 6, 4, 3 строк)')

# Второй источник: 11-16/0676r1, слайды 5–8 («11ad base matrix»).
for slajd, skor in ((8, '1/2'), (7, '5/8'), (6, '3/4'), (5, '13/16')):
    tabl, tekst_sl = tablicy_pptx('IEEE_802.11-16-0676-01_TGay_LDPC_1344.pptx', slajd)
    assert 'applied on this 11ad base matrix' in tekst_sl or slajd == 8, slajd
    baza = [chisla(t) for t in tabl if len(t[0]) == 16 and any(int(c) > 1 for r in t for c in r if c.lstrip('-').isdigit())]
    assert len(baza) == 1 and baza[0] == AD[skor], (skor, slajd)
print('802.11ad: те же матрицы в 11-16/0676r1 (слайды 5–8) — число в число')

# Систематичность, ранг, скорость.
KODY = {}
for skor, baza in AD.items():
    H = iz_bazy(baza)
    m, n = H.shape
    k = n - m
    assert gf2.ранг(H) == m and gf2.ранг(H[:, k:]) == m, skor      # полный ранг; данные — первые k
    a, b = map(int, skor.split('/'))
    assert k * b == n * a, skor
    KODY['80211ad-672-%d' % k] = {'семейство': 'IEEE 802.11ad (DMG)', 'n': n, 'k': k, 'скорость': skor, 'Z': Z,
                                  'база': baza, 'выколоты': [],
                                  'откуда': 'IEEE 802.11-10/0433r2 (TGad CP specification), 21.3.8, табл. %d; '
                                            '= 11-16/0676r1 (11ad base matrix)' % {'1/2': 69, '5/8': 70, '3/4': 71,
                                                                                  '13/16': 72}[skor]}
print('802.11ad: ранг H = n − k, проверочная часть полного ранга (систематический, данные — первые k): '
      + ', '.join('(%d, %d)' % (v['n'], v['k']) for v in KODY.values()))

# 7/8 (624, 546): выколоты первые 48 бит чётности 13/16 (11-16/1495r1, слайд 2).
_, s2 = tablicy_pptx('IEEE_802.11-16-1495-01_TGay_LDPC_7-8.pptx', 2)
s2 = re.sub(r'\s+', ' ', s2)
assert 'generated by puncturing the first 48 parity bits from rate 13/16 LDPC code words' in s2, s2
assert 'the codeword length is 624' in s2, s2
KODY['80211ad-624-546'] = dict(KODY['80211ad-672-546'], n=672, k=546, скорость='7/8', выколоты=list(range(546, 594)),
                               откуда='IEEE 802.11-2016 (REVmc) 7/8: 13/16 802.11ad без первых 48 бит чётности — '
                                      '11-16/1495r1, слайд 2')
print('802.11ad 7/8: (624, 546) = 13/16 без первых 48 бит чётности (позиции 546…593)')

# -- 6-циклы (11-16/0676r1, слайд 18) ---------------------------------------------------------------
tabl, _ = tablicy_pptx('IEEE_802.11-16-0676-01_TGay_LDPC_1344.pptx', 18)
cikly = {r[0]: (int(r[1]), int(r[2])) for t in tabl if t[0][0].startswith('Number of 6-cycles') for r in t[2:]}
assert set(cikly) == {'1/2', '5/8', '3/4', '13/16'}, cikly
for skor, baza in AD.items():
    assert shest_ciklov(iz_bazy(baza)) == cikly[skor][1], (skor, shest_ciklov(iz_bazy(baza)), cikly[skor])
print('6-циклы L672 (11ad) — как на слайде 18 11-16/0676r1: '
      + ', '.join('%s — %d' % (s, c[1]) for s, c in cikly.items()))

# -- 802.11ay 1344: подъём (11-16/0692r0 = 11-16/0676r1) ---------------------------------------------
POD = dict(zip(('1/2', '5/8', '3/4', '13/16'),
               (chisla(t) for t in tablicy_docx('IEEE_802.11-16-0692-00_TGay_SFD_LDPC_1344.docx')
                if t and len(t[0]) == 16 and all(re.fullmatch(r'-?[01]', c) for r in t for c in r))))
assert [len(p) for p in POD.values()] == [8, 6, 4, 3], POD
for slajd, skor in ((8, '1/2'), (7, '5/8'), (6, '3/4'), (5, '13/16')):
    tabl, _ = tablicy_pptx('IEEE_802.11-16-0676-01_TGay_LDPC_1344.pptx', slajd)
    pod = [chisla(t) for t in tabl if len(t[0]) == 16 and all(re.fullmatch(r'-?[01]', c) for r in t for c in r)]
    assert pod == [POD[skor]], skor
tekst92 = re.sub(r'\s+', ' ', open(os.path.join(ST, 'IEEE_802.11-16-0692-00_TGay_SFD_LDPC_1344.docx.txt'),
                                    encoding='utf-8').read())
assert "A ‘0’ in the lifting matrix acts on the Z×Z cyclic-permutation matrix Pi" in tekst92
print('802.11ay: матрицы подъёма 1344 — 11-16/0692r0 = 11-16/0676r1 (слайды 5–8)')


def podnyat(baza, pod):
    """«0» → [[Pi, −], [−, Pi]]; «1» → [[−, Pi], [Pi, −]]; «−1» (нулевой блок) → нули 2Z×2Z."""
    R, C = len(baza), len(baza[0])
    nov = [[-1] * (2 * C) for _ in range(2 * R)]
    for r in range(R):
        for c in range(C):
            if baza[r][c] < 0:
                assert pod[r][c] == -1, (r, c)
                continue
            assert pod[r][c] in (0, 1), (r, c)
            if pod[r][c] == 0:
                nov[2 * r][2 * c] = nov[2 * r + 1][2 * c + 1] = baza[r][c]
            else:
                nov[2 * r][2 * c + 1] = nov[2 * r + 1][2 * c] = baza[r][c]
    return nov


for skor in AD:
    baza = podnyat(AD[skor], POD[skor])
    H = iz_bazy(baza)
    m, n = H.shape
    k = n - m
    assert n == 1344 and gf2.ранг(H) == m and gf2.ранг(H[:, k:]) == m, skor
    assert shest_ciklov(H) == cikly[skor][0], (skor, shest_ciklov(H), cikly[skor])
    KODY['80211ay-1344-%d' % k] = {'семейство': 'IEEE 802.11ay (EDMG)', 'n': n, 'k': k, 'скорость': skor, 'Z': Z,
                                   'база': baza, 'выколоты': [],
                                   'откуда': 'IEEE 802.11-16/0692r0 (TGay SFD): подъём матрицы 802.11ad %s (= 11-16/0676r1); '
                                             '6-циклов %d — как на слайде 18' % (skor, cikly[skor][0])}
print('802.11ay 1344: четыре кода — ранг полный, данные — первые k, 6-циклы как на слайде 18: '
      + ', '.join('%s — %d' % (s, c[0]) for s, c in cikly.items()))

# 7/8 1344 (11-17/1061r1): подъём 3/4 по табл. 30, сумма строк 1+5, 2+6, 3+7, 4+8 = табл. 31.
t1061 = tablicy_docx('IEEE_802.11-17-1061-01_TGay_LDPC_1344_7-8.docx')
pod78 = [chisla(t) for t in t1061 if t and len(t[0]) == 16][0]
t31 = [chisla(t) for t in t1061 if t and len(t[0]) == 32][0]
assert len(pod78) == 4 and len(t31) == 4
podn = podnyat(AD['3/4'], pod78)
summa = []
for r in range(4):
    ryad = []
    for c in range(32):
        a, b = podn[r][c], podn[r + 4][c]
        assert a < 0 or b < 0, (r, c)            # блоки не перекрываются: сумма — снова циркулянт
        ryad.append(max(a, b))
    summa.append(ryad)
assert summa == t31, 'табл. 31 11-17/1061r1 не сошлась с подъёмом 3/4 802.11ad'
H = iz_bazy(t31)
assert H.shape == (168, 1344) and gf2.ранг(H) == 168 and gf2.ранг(H[:, 1176:]) == 168
KODY['80211ay-1344-1176'] = {'семейство': 'IEEE 802.11ay (EDMG)', 'n': 1344, 'k': 1176, 'скорость': '7/8', 'Z': Z,
                             'база': t31, 'выколоты': [],
                             'откуда': 'IEEE 802.11-17/1061r1 (TGay), табл. 31 = подъём 3/4 802.11ad по табл. 30 и '
                                       'сумма строк 1+5, 2+6, 3+7, 4+8'}
print('802.11ay 7/8 1344: табл. 31 = подъём 3/4 802.11ad (табл. 30) с суммой строк — число в число; ранг 168')

# -- третий голос: 802.11ad-phy-sim (не в репозитории) ----------------------------------------------
if len(sys.argv) > 1:
    m_ = open(os.path.join(sys.argv[1], 'LDPC_matrix.m')).read()
    kus = m_[m_.index('case 672'):m_.index('P0 = eye(Z)')]
    for imya, skor in (('FmR12', '1/2'), ('FmR58', '5/8'), ('FmR34', '3/4'), ('FmR1316', '13/16')):
        t = kus[kus.index(imya + '_template'):]
        t = t[t.index('[...') + 4:t.index('];')]
        ryady = [[-1 if x == 'NaN' else int(x) for x in s.replace(';', ' ').split()] for s in t.split('\n') if s.strip()]
        assert ryady == AD[skor], skor
    assert 'puncturing' in kus[kus.index('case 624'):] or 'punctured' in kus[kus.index('case 624'):]
    print('802.11ad-phy-sim (f986bfc): четыре матрицы 672 — те же; 624 — выколотая 13/16')

put = os.path.join(KOREN, 'src', 'reportgen', 'potok', 'data', 'ldpc_80211ad.json')
with open(put, 'w', encoding='utf-8') as f:
    json.dump(KODY, f, ensure_ascii=False, separators=(',', ':'))
print('Записано: %s — %d кодов' % (os.path.relpath(put, KOREN), len(KODY)))
